% % survey_clustering =  [2 0 0 1 1 0 0 1 2 2 1 1 2 1];
% % survey_clustering = [1 0 0 0 0 0 0 2 1 1 0 0 1 2];
% survey_clustering = [2 0 0 1 1 0 0 1 0 0 1 1 0 1];
% load('/home/zzw/Dropbox (ESP Lab)/research on context awareness/experiment/monday/wifi-data/entropy_all_statistical_features_without_writing.mat')
% load('/home/zzw/Dropbox (ESP Lab)/research on context awareness/experiment/monday/wifi-data/entropy_distance_mean_std_without_writing.mat');
% load('/home/zzw/Dropbox (ESP Lab)/research on context awareness/experiment/monday/wifi-data/motion_level_distance_mean_std_without_writing.mat');
%  
% writing_result = load('monday/wifi-data/writing_all.txt');
% time_list = load('monday/time.txt');
% slides_num = length(time_list) / 2;
% writing_mat = {};
% last_index = 1;
% last_row = [];
% for t = 1:2:length(time_list)
%     current_end_t = time_list(t + 1);
%     if t == length(time_list) - 1
%         writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:end,:)];
%         break;
%     end
%     for i = last_index:length(writing_result(:,1))
%         if writing_result(i,2) > current_end_t
%             writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i - 1,:); writing_result(i - 1,1) current_end_t];
%             last_row = [writing_result(i - 1,1) current_end_t];
%             last_index = i;
%             break;
%         elseif writing_result(i,2) == current_end_t  
%             writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i,:)];
%             last_row = [];
%             last_index = i + 1;
%             break;
%         end
%     end
% end
%  
% writing_max_list = zeros(1,slides_num);
% writing_min_list = zeros(1,slides_num);
% writing_average_list = zeros(1,slides_num);
% writing_longest_num_list = zeros(1,slides_num);
%  
% features_mat = [];
% for i = 1:slides_num
%     writing_max_list(i) = max(writing_mat{i}(:,1));
%     writing_min_list(i) = min(writing_mat{i}(:,1));
%     writing_time_duration_list = writing_mat{i}(2:2:length(writing_mat{i}(:,1)),2)...
%         - writing_mat{i}(1:2:length(writing_mat{i}(:,1)),2);
%     writing_average_list(i) = sum(writing_time_duration_list .*...
%         writing_mat{i}(1:2:length(writing_mat{i}(:,1)),1))...
%         / sum(writing_time_duration_list);
%     [longest_time, longest_index] = max(writing_time_duration_list);
%     writing_longest_num_list(i) = writing_mat{i}(longest_index * 2, 1);
%     features_mat(i,:) = [...
%         writing_max_list(i), writing_min_list(i), writing_average_list(i), writing_longest_num_list(i),...
%         en_group_mean_list(i,:), en_group_std_list(i,:),...
%         en_group_rms_list(i,:), en_group_var_list(i,:),...
%         en_group_skewness_list(i,:), en_group_kurtosis_list(i,:),...
%         en_group_mcr_list(i,:),...
%         ml_group_mean_list(i,:), ml_group_std_list(i,:),...
%         ml_group_rms_list(i,:), ml_group_var_list(i,:),...
%         ml_group_skewness_list(i,:), ml_group_kurtosis_list(i,:),...
%         ml_group_mcr_list(i,:),...
%         en_acc_dist_mean(i), en_acc_dist_std(i),...
%         en_gyr_dist_mean(i), en_gyr_dist_std(i), ml_acc_dist_mean(i),...
%         ml_acc_dist_std(i), ml_gyr_dist_mean(i), ml_gyr_dist_std(i), survey_clustering(i)];
% end
%  
% load('/home/zzw/Dropbox (ESP Lab)/research on context awareness/experiment/wednesday/wifi-data/entropy_all_statistical_features_without_writing.mat');
% load('/home/zzw/Dropbox (ESP Lab)/research on context awareness/experiment/wednesday/wifi-data/entropy_distance_mean_std_without_writing.mat');
% load('/home/zzw/Dropbox (ESP Lab)/research on context awareness/experiment/wednesday/wifi-data/motion_level_distance_mean_std_without_writing.mat');
%  
% writing_result = load('wednesday/wifi-data/writing_all.txt');
% time_list = load('wednesday/time.txt');
% slides_num = length(time_list) / 2;
% writing_mat = {};
% last_index = 1;
% last_row = [];
% for t = 1:2:length(time_list)
%     current_end_t = time_list(t + 1);
%     if t == length(time_list) - 1
%         writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:end,:)];
%         break;
%     end
%     for i = last_index:length(writing_result(:,1))
%         if writing_result(i,2) > current_end_t
%             writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i - 1,:); writing_result(i - 1,1) current_end_t];
%             last_row = [writing_result(i - 1,1) current_end_t];
%             last_index = i;
%             break;
%         elseif writing_result(i,2) == current_end_t  
%             writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i,:)];
%             last_row = [];
%             last_index = i + 1;
%             break;
%         end
%     end
% end
%  
% writing_max_list = zeros(1,slides_num);
% writing_min_list = zeros(1,slides_num);
% writing_average_list = zeros(1,slides_num);
% writing_longest_num_list = zeros(1,slides_num);
%  
% for i = 1:slides_num
%     writing_max_list(i) = max(writing_mat{i}(:,1));
%     writing_min_list(i) = min(writing_mat{i}(:,1));
%     writing_time_duration_list = writing_mat{i}(2:2:length(writing_mat{i}(:,1)),2)...
%         - writing_mat{i}(1:2:length(writing_mat{i}(:,1)),2);
%     writing_average_list(i) = sum(writing_time_duration_list .*...
%         writing_mat{i}(1:2:length(writing_mat{i}(:,1)),1))...
%         / sum(writing_time_duration_list);
%     [longest_time, longest_index] = max(writing_time_duration_list);
%     writing_longest_num_list(i) = writing_mat{i}(longest_index * 2, 1);
%     features_mat(i + 8,:) = [...
%         writing_max_list(i), writing_min_list(i), writing_average_list(i), writing_longest_num_list(i),...
%         en_group_mean_list(i,:), en_group_std_list(i,:),...
%         en_group_rms_list(i,:), en_group_var_list(i,:),...
%         en_group_skewness_list(i,:), en_group_kurtosis_list(i,:),...
%         en_group_mcr_list(i,:),...
%         ml_group_mean_list(i,:), ml_group_std_list(i,:),...
%         ml_group_rms_list(i,:), ml_group_var_list(i,:),...
%         ml_group_skewness_list(i,:), ml_group_kurtosis_list(i,:),...
%         ml_group_mcr_list(i,:),...
%         en_acc_dist_mean(i), en_acc_dist_std(i),...
%         en_gyr_dist_mean(i), en_gyr_dist_std(i), ml_acc_dist_mean(i),...
%         ml_acc_dist_std(i), ml_gyr_dist_mean(i), ml_gyr_dist_std(i), survey_clustering(i + 8)];
% end
%  
% csvwrite('input_difficulty_without_writing.csv',features_mat);




close all;
clear all;
% survey_clustering =  [2 0 0 1 1 0 0 1 2 2 1 1 2 1];
survey_clustering = [1 0 0 0 0 0 0 2 1 1 0 0 1 2]; % interest
% survey_clustering = [2 0 0 1 1 0 0 1 0 0 1 1 0 1]; % difficulty
 
writing_rate_mean_list = zeros(1,length(survey_clustering));
writing_rate_std_list = zeros(1,length(survey_clustering));
writing_rate_var_list = zeros(1,length(survey_clustering));
writing_rate_rms_list = zeros(1,length(survey_clustering));
writing_rate_file = fopen('slide_writing_rate_list.txt');
for i = 1:length(survey_clustering)
    row_text = fgets(writing_rate_file);
    cell_array = strsplit(row_text, ' ');
    row_rate_list = str2num(char(cell_array));
    writing_rate_mean_list(i) = mean(row_rate_list);
    writing_rate_std_list(i) = std(row_rate_list);
    writing_rate_var_list(i) = var(row_rate_list);
    writing_rate_rms_list(i) = rms(row_rate_list);
end
 
load('monday/wifi-data/amplitude_everyone_normalized_statistical_features.mat');
load('monday/wifi-data/entropy_all_statistical_features_without_writing.mat')
load('monday/wifi-data/entropy_distance_statistical_features_ww_n.mat');
load('monday/wifi-data/entropy_everyone_normalized_statistical_features.mat');
load('monday/wifi-data/motion_level_all_statistical_features_without_writing.mat');
load('monday/wifi-data/motion_level_distance_statistical_features_ww_n.mat');
load('monday/wifi-data/motion_level_everyone_normalized_statistical_features.mat');
 
writing_result = load('monday/wifi-data/writing_all.txt');
time_list = load('monday/time.txt');
slides_num = length(time_list) / 2;
writing_mat = {};
last_index = 1;
last_row = [];
for t = 1:2:length(time_list)
    current_end_t = time_list(t + 1);
    if t == length(time_list) - 1
        writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:end,:)];
        break;
    end
    for i = last_index:length(writing_result(:,1))
        if writing_result(i,2) > current_end_t
            writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i - 1,:); writing_result(i - 1,1) current_end_t];
            last_row = [writing_result(i - 1,1) current_end_t];
            last_index = i;
            break;
        elseif writing_result(i,2) == current_end_t  
            writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i,:)];
            last_row = [];
            last_index = i + 1;
            break;
        end
    end
end
 
writing_max_list = zeros(1,slides_num);
writing_min_list = zeros(1,slides_num);
writing_average_list = zeros(1,slides_num);
writing_longest_num_list = zeros(1,slides_num);
 
features_mat = [];
for i = 1:slides_num
    writing_max_list(i) = max(writing_mat{i}(:,1));
    writing_min_list(i) = min(writing_mat{i}(:,1));
    writing_time_duration_list = writing_mat{i}(2:2:length(writing_mat{i}(:,1)),2)...
        - writing_mat{i}(1:2:length(writing_mat{i}(:,1)),2);
    writing_average_list(i) = sum(writing_time_duration_list .*...
        writing_mat{i}(1:2:length(writing_mat{i}(:,1)),1))...
        / sum(writing_time_duration_list);
    [longest_time, longest_index] = max(writing_time_duration_list);
    writing_longest_num_list(i) = writing_mat{i}(longest_index * 2, 1);
    features_mat(i,:) = [...
        writing_max_list(i), writing_min_list(i), writing_average_list(i), writing_longest_num_list(i),...
        writing_rate_mean_list(i),...
        writing_rate_std_list(i),...
        writing_rate_var_list(i),...
        writing_rate_rms_list(i),...
        en_group_mean_list(i,:), en_group_std_list(i,:),...
        en_group_rms_list(i,:), en_group_var_list(i,:),...
        en_group_skewness_list(i,:), en_group_kurtosis_list(i,:),...
        en_group_mcr_list(i,:),...
        ml_group_mean_list(i,:), ml_group_std_list(i,:),...
        ml_group_rms_list(i,:), ml_group_var_list(i,:),...
        ml_group_skewness_list(i,:), ml_group_kurtosis_list(i,:),...
        ml_group_mcr_list(i,:),...
        amp_everyone_normalized_mean_list(i,:),...
        amp_everyone_normalized_std_list(i,:),...
        amp_everyone_normalized_var_list(i,:),...
        amp_everyone_normalized_rms_list(i,:),...
        en_everyone_normalized_mean_list(i,:),...
        en_everyone_normalized_std_list(i,:),...
        en_everyone_normalized_var_list(i,:),...
        en_everyone_normalized_rms_list(i,:),...
        ml_everyone_normalized_mean_list(i,:),...
        ml_everyone_normalized_std_list(i,:),...
        ml_everyone_normalized_var_list(i,:),...
        ml_everyone_normalized_rms_list(i,:),...
        en_dist_mean_list(i,:),...
        en_dist_std_list(i,:),...
        en_dist_var_list(i,:),...
        en_dist_rms_list(i,:),...
        ml_dist_mean_list(i,:),...
        ml_dist_std_list(i,:),...
        ml_dist_var_list(i,:),...
        ml_dist_rms_list(i,:),...
        survey_clustering(i)];
end
 
load('wednesday/wifi-data/amplitude_everyone_normalized_statistical_features.mat');
load('wednesday/wifi-data/entropy_all_statistical_features_without_writing.mat')
load('wednesday/wifi-data/entropy_distance_statistical_features_ww_n.mat');
load('wednesday/wifi-data/entropy_everyone_normalized_statistical_features.mat');
load('wednesday/wifi-data/motion_level_all_statistical_features_without_writing.mat');
load('wednesday/wifi-data/motion_level_distance_statistical_features_ww_n.mat');
load('wednesday/wifi-data/motion_level_everyone_normalized_statistical_features.mat');
 
writing_result = load('wednesday/wifi-data/writing_all.txt');
time_list = load('wednesday/time.txt');
slides_num = length(time_list) / 2;
writing_mat = {};
last_index = 1;
last_row = [];
for t = 1:2:length(time_list)
    current_end_t = time_list(t + 1);
    if t == length(time_list) - 1
        writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:end,:)];
        break;
    end
    for i = last_index:length(writing_result(:,1))
        if writing_result(i,2) > current_end_t
            writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i - 1,:); writing_result(i - 1,1) current_end_t];
            last_row = [writing_result(i - 1,1) current_end_t];
            last_index = i;
            break;
        elseif writing_result(i,2) == current_end_t  
            writing_mat{(t + 1) / 2} = [last_row; writing_result(last_index:i,:)];
            last_row = [];
            last_index = i + 1;
            break;
        end
    end
end
 
writing_max_list = zeros(1,slides_num);
writing_min_list = zeros(1,slides_num);
writing_average_list = zeros(1,slides_num);
writing_longest_num_list = zeros(1,slides_num);
 
for i = 1:slides_num
    writing_max_list(i) = max(writing_mat{i}(:,1));
    writing_min_list(i) = min(writing_mat{i}(:,1));
    writing_time_duration_list = writing_mat{i}(2:2:length(writing_mat{i}(:,1)),2)...
        - writing_mat{i}(1:2:length(writing_mat{i}(:,1)),2);
    writing_average_list(i) = sum(writing_time_duration_list .*...
        writing_mat{i}(1:2:length(writing_mat{i}(:,1)),1))...
        / sum(writing_time_duration_list);
    [longest_time, longest_index] = max(writing_time_duration_list);
    writing_longest_num_list(i) = writing_mat{i}(longest_index * 2, 1);
    features_mat(i + 8,:) = [...
       writing_max_list(i), writing_min_list(i), writing_average_list(i), writing_longest_num_list(i),...
        writing_rate_mean_list(i + 8),...
        writing_rate_std_list(i + 8),...
        writing_rate_var_list(i + 8),...
        writing_rate_rms_list(i + 8),...
        en_group_mean_list(i,:), en_group_std_list(i,:),...
        en_group_rms_list(i,:), en_group_var_list(i,:),...
        en_group_skewness_list(i,:), en_group_kurtosis_list(i,:),...
        en_group_mcr_list(i,:),...
        ml_group_mean_list(i,:), ml_group_std_list(i,:),...
        ml_group_rms_list(i,:), ml_group_var_list(i,:),...
        ml_group_skewness_list(i,:), ml_group_kurtosis_list(i,:),...
        ml_group_mcr_list(i,:),...
        amp_everyone_normalized_mean_list(i,:),...
        amp_everyone_normalized_std_list(i,:),...
        amp_everyone_normalized_var_list(i,:),...
        amp_everyone_normalized_rms_list(i,:),...
        en_everyone_normalized_mean_list(i,:),...
        en_everyone_normalized_std_list(i,:),...
        en_everyone_normalized_var_list(i,:),...
        en_everyone_normalized_rms_list(i,:),...
        ml_everyone_normalized_mean_list(i,:),...
        ml_everyone_normalized_std_list(i,:),...
        ml_everyone_normalized_var_list(i,:),...
        ml_everyone_normalized_rms_list(i,:),...
        en_dist_mean_list(i,:),...
        en_dist_std_list(i,:),...
        en_dist_var_list(i,:),...
        en_dist_rms_list(i,:),...
        ml_dist_mean_list(i,:),...
        ml_dist_std_list(i,:),...
        ml_dist_var_list(i,:),...
        ml_dist_rms_list(i,:),...
        survey_clustering(i + 8)];
end
 
csvwrite('input_interest_ww_n.csv',features_mat);
% [6, 18, 12, 9, 23]