name_list = ['mixed SDANN every 30 seconds mean',
                'mixed SDANN every 30 seconds std',
                'mixed SDANN every 30 seconds var',
                'mixed SDANN every 30 seconds rms',
                'mixed SDNNIDX every 30 seconds mean',
                'mixed SDNNIDX every 30 seconds std',
                'mixed SDNNIDX every 30 seconds var',
                'mixed SDNNIDX every 30 seconds rms',
                'mixed SDANN every 1 minute mean',
                'mixed SDANN every 1 minute std',
                'mixed SDANN every 1 minute var',
                'mixed SDANN every 1 minute rms',
                'mixed SDNNIDX every 1 minute mean',
                'mixed SDNNIDX every 1 minute std',
                'mixed SDNNIDX every 1 minute var',
                'mixed SDNNIDX every 1 minute rms',
                'mixed SDANN every 2 minutes mean',
                'mixed SDANN every 2 minutes std',
                'mixed SDANN every 2 minutes var',
                'mixed SDANN every 2 minutes rms',
                'mixed SDNNIDX every 2 minutes mean',
                'mixed SDNNIDX every 2 minutes std',
                'mixed SDNNIDX every 2 minutes var',
                'mixed SDNNIDX every 2 minutes rms',
                'mixed SDANN every 5 minutes mean',
                'mixed SDANN every 5 minutes std',
                'mixed SDANN every 5 minutes var',
                'mixed SDANN every 5 minutes rms',
                'mixed SDNNIDX every 5 minutes mean',
                'mixed SDNNIDX every 5 minutes std',
                'mixed SDNNIDX every 5 minutes var',
                'mixed SDNNIDX every 5 minutes rms',
                'mixed individual heart rate mean',
                'mixed individual heart rate std',
                'mixed individual heart rate var',
                'mixed individual heart rate rms',
                'group writing episodes maximum',
                'group writing episodes minmum',
                'group writing episodes mean',
                'group writing episodes number of students of the longest lasting time',
                'individual writing episodes mean',
                'individual writing episodes standard deviation',
                'individual writing episodes variance',
                'individual writing episodes root mean squre',
                'group entropy mean acc',
                'group entropy mean gyr',
                'group entropy std acc',
                'group entropy std gyr',
                'group entropy rms acc',
                'group entropy rms gyr',
                'group entropy var acc',
                'group entropy var gyr',
                'group entropy skewness acc',
                'group entropy skewness gyr',
                'group entropy kurtosis acc',
                'group entropy kurtosis gyr',
                'group entropy mean crossing rate acc',
                'group entropy mean crossing rate gyr',
                'group estimated magnitude mean acc',
                'group estimated magnitude mean gyr',
                'group estimated magnitude std acc',
                'group estimated magnitude std gyr',
                'group estimated magnitude rms acc',
                'group estimated magnitude rms gyr',
                'group estimated magnitude var acc',
                'group estimated magnitude var gyr',
                'group estimated magnitude skewness acc',
                'group estimated magnitude skewness gyr',
                'group estimated magnitude kurtosis acc',
                'group estimated magnitude kurtosis gyr',
                'group estimated magnitude mean crossing rate acc',
                'group estimated magnitude mean crossing rate gyr',
                'mixed and normalized individual amplitude mean acc',
                'mixed and normalized individual amplitude mean gyr',
                'mixed and normalized individual amplitude std acc',
                'mixed and normalized individual amplitude std gyr',
                'mixed and normalized individual amplitude var acc',
                'mixed and normalized individual amplitude var gyr',
                'mixed and normalized individual amplitude rms acc',
                'mixed and normalized individual amplitude rms gyr',
                'mixed and normalized individual entropy mean acc',
                'mixed and normalized individual entropy mean gyr',
                'mixed and normalized individual entropy std acc',
                'mixed and normalized individual entropy std gyr',
                'mixed and normalized individual entropy var acc',
                'mixed and normalized individual entropy var gyr',
                'mixed and normalized individual entropy rms acc',
                'mixed and normalized individual entropy rms gyr',
                'mixed and normalized individual estimated magnitude mean acc',
                'mixed and normalized individual estimated magnitude mean gyr',
                'mixed and normalized individual estimated magnitude std acc',
                'mixed and normalized individual estimated magnitude std gyr',
                'mixed and normalized individual estimated magnitude var acc',
                'mixed and normalized individual estimated magnitude var gyr',
                'mixed and normalized individual estimated magnitude rms acc',
                'mixed and normalized individual estimated magnitude rms gyr',
                'distance set of individual entropy mean acc',
                'distance set of individual entropy mean gyr',
                'distance set of individual entropy std acc',
                'distance set of individual entropy std gyr',
                'distance set of individual entropy var acc',
                'distance set of individual entropy var gyr',
                'distance set of individual entropy rms acc',
                'distance set of individual entropy rms gyr',
                'distance set of individual estimated magnitude mean acc',
                'distance set of individual estimated magnitude mean gyr',
                'distance set of individual estimated magnitude std acc',
                'distance set of individual estimated magnitude std gyr',
                'distance set of individual estimated magnitude var acc',
                'distance set of individual estimated magnitude var gyr',
                'distance set of individual estimated magnitude rms acc',
                'distance set of individual estimated magnitude rms gyr']

# rank_list_i = [88,82,81,46,87,50,45,91,93,49,83,85,90,75,77,60,40,79,84,102,86,100,73,74,96,64,53,95,57,11,24,89,10,21,
#                92,94,28,80,76,1,78,62,104,26,39,58,19,98,56,27,66,109,4,110,18,47,48,107,52,25,37,103,36,33,32,97,108,
#                51,13,99,12,55,101,65,59,63,2,30,29,111,67,54,71,8,16,5,105,3,31,68,17,41,7,6,9,38,44,14,70,61,22,15,23,
#                34,20,35,69,72,43,106,42,112]
#
# rank_list_d = [42,43,112,108,106,110,56,48,13,16,52,34,35,28,82,92,87,88,81,96,62,94,50,83,61,25,46,85,90,76,80,74,105,
#                111,78,64,38,66,107,47,97,60,8,49,5,33,36,45,103,71,72,51,59,63,65,67,55,109,69,100,98,102,104,14,15,1,
#                20,37,17,7,6,29,32,9,24,57,4,70,21,10,11,77,79,73,54,75,41,18,99,30,68,2,19,101,84,3,86,39,89,95,27,91,
#                12,26,31,58,93,44,53,40,23,22]
#
# # for i in rank_list_i:
# #     print(name_list[i - 1])
# for i in rank_list_d:
#     print(name_list[i - 1])

feature_select_list = [[25, 32, 34, 49, 80, 98, 105], [3, 25, 31, 45, 80, 94, 95, 98], [3, 38, 43, 45, 49, 67, 80, 81, 86, 87, 98, 99, 107, 109],
               [45, 49, 53, 64, 65, 81, 87, 89, 90], [28, 37, 47, 51, 80], [21, 22, 28, 47, 51, 80, 82, 87, 95, 108],
               [34, 41, 45, 49, 55, 81, 85, 87, 99, 101], [7, 21, 22, 41, 53, 61, 90, 111]]

for i in feature_select_list:
    for j in i:
        print(name_list[j])
    print